HopDongBanA/Models/HT_NguoiDung.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongMgr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HT_NguoiDung()
        {
            this.CN_HopDong = new HashSet<CN_HopDong>();
        }
    
        public System.Guid oid { get; set; }
        public string MaNguoiDung { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string AnhDaiDien { get; set; }
        public string MaDV { get; set; }
        public Nullable<System.Guid> IdNhom { get; set; }
        public Nullable<System.Guid> IdPhong { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.Guid> ChucVu { get; set; }
        public Nullable<int> NamSinh { get; set; }
        public bool Active { get; set; }
        public string BiDanh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CN_HopDong> CN_HopDong { get; set; }
        public virtual HT_CHUCVU HT_CHUCVU { get; set; }
    }
}

HopDongBanA/Controllers/HT_NguoiDungController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HopDongMgr.Models;
using HopDongMgr.DungChung;
using HopDongMgr.Class.Common;
using System.Data.SqlClient;

namespace HopDongMgr.Controllers
{
    public class HT_NguoiDungController : Controller
    {
        private HopDongMgrEntities db = new HopDongMgrEntities();

        // GET: HT_NguoiDung
        [CustomAuthorization]
        public ActionResult Index()
        {
            //var hT_NguoiDung = db.HT_NguoiDung.Include(h => h.).Include(h => h.HT_Nhom).OrderBy(a => a.MaDV);
            return View(db.HT_NguoiDung.ToList());
        }

        // GET: HT_NguoiDung/Details/5
        [CustomAuthorization]
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HT_NguoiDung hT_NguoiDung = db.HT_NguoiDung.Find(id);
            hT_NguoiDung.MatKhau = Common.EncryptMD5(hT_NguoiDung.MatKhau);
            if (hT_NguoiDung == null)
            {
                return HttpNotFound();
            }
            return View(hT_NguoiDung);
        }

        // GET: HT_NguoiDung/Create
        [CustomAuthorization]
        public ActionResult Create()
        {
            string maDV = Session["MaDV"].ToString();
            ViewBag.MaDV = new SelectList(db.DM_DONVI.Where(a => a.MA_DVIQLY.Contains(maDV)), "MA_DVIQLY", "TEN_DVIQLY");
            ViewBag.IdNhom = new SelectList(db.HT_Nhom.Where(a => a.MaDV == maDV).OrderBy(a => a.Ten), "Id", "Ten");
            ViewBag.IdPhong = new SelectList(db.DM_PHONG.Where(a => a.MaDV == maDV).OrderBy(a => a.Ten), "Id", "Ten");
            ViewBag.GioiTinh = Common.GioiTinh("");
            ViewBag.ChucVu = new SelectList(db.HT_CHUCVU.OrderBy(a => a.Ten), "Id", "Ten");
            return View();
        }

        // POST: HT_NguoiDung/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "oid,MaNguoiDung,MatKhau,HoTen,Email,AnhDaiDien,MaDV,IdNhom,IdPhong,GioiTinh,ChucVu,Active,BiDanh")] HT_NguoiDung hT_NguoiDung, HttpPostedFileBase photo)
        {
            string maDV = Session["MaDV"].ToString();
            ViewBag.MaDV = new SelectList(db.DM_DONVI.Where(a => a.MA_DVIQLY.Contains(maDV)), "MA_DVIQLY", "TEN_DVIQLY");
            ViewBag.IdNhom = new SelectList(db.HT_Nhom.Where(a => a.MaDV == maDV).OrderBy(a => a.Ten), "Id", "Ten");
            ViewBag.IdPhong = new SelectList(db.DM_PHONG.Where(a => a.MaDV == maDV).OrderBy(a => a.Ten), "Id", "Ten");
            ViewBag.GioiTinh = Common.GioiTinh("");
            ViewBag.ChucVu = new SelectList(db.HT_CHUCVU.OrderBy(a => a.Ten), "Id", "Ten", hT_NguoiDung.ChucVu);
            if (string.IsNullOrEmpty(hT_NguoiDung.MaNguoiDung))
            {
                TempData["err"] = "<div class='alert alert-info' role='alert'><span class='glyphicon glyphicon-exclamation - sign' aria-hidden='true'></span><span class='sr - only'></span>Vui lòng điền mã người dùng</div> ";
                return View(hT_NguoiDung);
            }
            List<HT_NguoiDung> nd = db.HT_NguoiDung.Where(a => a.MaNguoiDung == hT_NguoiDung.MaNguoiDung).ToList();
            if (nd.Count > 0)
            {
                TempData["err"] = "<div class='alert alert-info' role='alert'><span class='glyphicon glyphicon-exclamation - sign' aria-hidden='true'></span><span class='sr - only'></span>Mã người dùng đã tồn tại</div> ";
                return View(hT_NguoiDung);
            }
            if (string.IsNullOrEmpty(hT_NguoiDung.HoTen))
            {
                TempData["err"] = "<div class='alert alert-info' role='alert'><span class='glyphicon glyphicon-exclamation - sign' aria-hidden='true'></span><span class='sr - only'></span>Vui lòng điền đầy đủ họ tên</div> ";
                return View(hT_NguoiDung);
            }
            if (ModelState.IsValid)
            {
                if (string.IsNullOrEmpty(hT_NguoiDung.MatKhau))
                {
                    TempData["err"] = "<div class='alert alert-info' role='alert'><span class='glyphicon glyphicon-exclamation - sign' aria-hidden='true'></span><span class='sr - only'></span>Vui lòng nhập mật khẩu</div> ";
                    return View(hT_NguoiDung);
                }
                hT_NguoiDung.oid = Guid.NewGuid();
                hT_NguoiDung.MatKhau = Common.EncryptMD5(hT_NguoiDung.MatKhau);
                if (photo != null)
                {
                    var fileName = Guid.NewGuid().ToString() + "_" + photo.FileName;
                    hT_NguoiDung.AnhDaiDien = fileName;
                    UploadPhoto(fileName, photo);
                }
                else
                    hT_NguoiDung.AnhDaiDien = "avatar.png";
                Session["avatar"] = hT_NguoiDung.AnhDaiDien;
                db.HT_NguoiDung.Add(hT_NguoiDung);
                db.SaveChanges();
                HT_LichSuHoatDong ls = new HT_LichSuHoatDong(
                this.ControllerContext.RouteData.Values["controller"].ToString()
                , "CREATE"
                , DateTime.Now, Session["username"]?.ToString()
                , $" {this.ControllerContext.RouteData.Values["action"]?.ToString()} - {hT_NguoiDung.MaNguoiDung} ");
                db.HT_LichSuHoatDong.Add(ls);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hT_NguoiDung);
        }

        // GET: HT_NguoiDung/Edit/5
        [CustomAuthorization]
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            string maDV = Session["MaDV"].ToString();
            HT_NguoiDung hT_NguoiDung = db.HT_NguoiDung.Find(id);
            if (hT_NguoiDung == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaDV = new SelectList(db.DM_DONVI.Where(a => a.MA_DVIQLY.Contains(maDV)), "MA_DVIQLY", "TEN_DVIQLY", hT_NguoiDung.MaDV);
            ViewBag.IdNhom = new SelectList(db.HT_Nhom.Where(a => a.MaDV == hT_NguoiDung.MaDV).OrderBy(a => a.Ten), "Id", "Ten", hT_NguoiDung.IdNhom);
            ViewBag.IdPhong = new SelectList(db.DM_PHONG.Where(a => a.MaDV == hT_NguoiDung.MaDV).OrderBy(a => a.Ten), "Id", "Ten", hT_NguoiDung.IdPhong);

            ViewBag.GioiTinh = Common.GioiTinh(hT_NguoiDung.GioiTinh);
            ViewBag.ChucVu = new SelectList(db.HT_CHUCVU.OrderBy(a => a.Ten), "Id", "Ten", hT_NguoiDung.ChucVu);
            if (string.IsNullOrEmpty(hT_NguoiDung.AnhDaiDien))
                hT_NguoiDung.AnhDaiDien = "avatar.png";
            Session["avatar"] = hT_NguoiDung.AnhDaiDien;
            hT_NguoiDung.MatKhau = "";
            return View(hT_NguoiDung);
        }

        // POST: HT_NguoiDung/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "oid,MaNguoiDung,MatKhau,HoTen,Email,AnhDaiDien,MaDV,IdNhom,IdPhong,GioiTinh,ChucVu,Active,BiDanh")] HT_NguoiDung hT_NguoiDung, HttpPostedFileBase photo)
        {
            if (ModelState.IsValid)
            {
                string maDV = Session["MaDV"].ToString();
                ViewBag.MaDV = new SelectList(db.DM_DONVI.Where(a => a.MA_DVIQLY.Contains(maDV)), "MA_DVIQLY", "TEN_DVIQLY", hT_NguoiDung.MaDV);
                ViewBag.IdNhom = new SelectList(db.HT_Nhom.Where(a => a.MaDV == hT_NguoiDung.MaDV).OrderBy(a => a.Ten), "Id", "Ten", hT_NguoiDung.IdNhom);
                ViewBag.IdPhong = new SelectList(db.DM_PHONG.Where(a => a.MaDV == hT_NguoiDung.MaDV).OrderBy(a => a.Ten), "Id", "Ten", hT_NguoiDung.IdPhong);
                ViewBag.GioiTinh = Common.GioiTinh(hT_NguoiDung.GioiTinh);
                ViewBag.ChucVu = new SelectList(db.HT_CHUCVU.OrderBy(a => a.Ten), "Id", "Ten", hT_NguoiDung.ChucVu);
                if (string.IsNullOrEmpty(hT_NguoiDung.MaNguoiDung))
                {
                    TempData["err"] = "<div class='alert alert-info' role='alert'><span class='glyphicon glyphicon-exclamation - sign' aria-hidden='true'></span><span class='sr - only'></span>Vui lòng điền mã người dùng</div> ";
                    return View(hT_NguoiDung);
                }
                if (string.IsNullOrEmpty(hT_NguoiDung.MatKhau))
                {
                    TempData["err"] = "<div class='alert alert-info' role='alert'><span class='glyphicon glyphicon-exclamation - sign' aria-hidden='true'></span><span class='sr - only'></span>Vui lòng nhập mật khẩu</div> ";
                    return View(hT_NguoiDung);
                }
                if (string.IsNullOrEmpty(hT_NguoiDung.HoTen))
                {
                    TempData["err"] = "<div class='alert alert-info' role='alert'><span class='glyphicon glyphicon-exclamation - sign' aria-hidden='true'></span><span class='sr - only'></span>Vui lòng điền đầy đủ họ tên</div> ";
                    return View(hT_NguoiDung);
                }
                hT_NguoiDung.MatKhau = Common.EncryptMD5(hT_NguoiDung.MatKhau);
                if (photo != null)
                {
                    var fileName = Guid.NewGuid().ToString() + "_" + photo.FileName;
                    hT_NguoiDung.AnhDaiDien = fileName;
                    UploadPhoto(fileName, photo);
                }
                else
                {
                    hT_NguoiDung.AnhDaiDien = "avatar.png";
                }

HopDongBanA/Views/HT_NguoiDung/Create.cshtml
@model HopDongMgr.Models.HT_NguoiDung

@{
    ViewBag.Title = "THÊM MỚI NGƯỜI DÙNG";
}

<div>
    @Html.Raw(TempData["err"])
</div>
@using (Html.BeginForm("Create", "HT_NguoiDung", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            @*@Html.LabelFor(model => model.MaNguoiDung, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Mã người dùng</label>
            <div class="col-md-4">
                @Html.EditorFor(model => model.MaNguoiDung, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaNguoiDung, "", new { @class = "text-danger" })
            </div>
            <label class="control-label col-md-2">Mật khẩu</label>
            <div class="col-md-4">
                @Html.EditorFor(model => model.MatKhau, new { htmlAttributes = new { @class = "form-control", placeholder = "Mật khẩu", @type = "password" } })
                @Html.ValidationMessageFor(model => model.MatKhau, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group  row">
            @*@Html.LabelFor(model => model.HoTen, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Họ tên</label>
            <div class="col-md-4">
                @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoTen, "", new { @class = "text-danger" })
            </div>
            <label class="control-label col-md-2">Bí danh</label>
            <div class="col-md-4">
                @Html.EditorFor(model => model.BiDanh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BiDanh, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group  row">
            @*@Html.LabelFor(model => model.MaDV, "MaDV", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Đơn vị quản lý</label>
            <div class="col-md-4">
                @Html.DropDownList("MaDV", null, htmlAttributes: new { @class = "form-control", @id = "cbDonVi", @onchange = "DonViOnChange()" })
                @Html.ValidationMessageFor(model => model.MaDV, "", new { @class = "text-danger" })
            </div>
            <label class="control-label col-md-2">Phòng ban</label>
            <div class="col-md-4">
                @Html.DropDownList("IdPhong", null, htmlAttributes: new { @class = "form-control", @id = "cbPhong" })
                @Html.ValidationMessageFor(model => model.IdPhong, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group  row">
            <label class="control-label col-md-2">Chức vụ</label>
            <div class="col-md-4">
                @Html.DropDownList("ChucVu", null, "-- Không chọn --", htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ChucVu, "", new { @class = "text-danger" })
            </div>
            <label class="control-label col-md-2">Nhóm người dùng</label>
            <div class="col-md-4">
                @Html.DropDownList("IdNhom", null, "-- Không chọn --", htmlAttributes: new { @class = "form-control", @id = "cbNhom" })
                @Html.ValidationMessageFor(model => model.IdNhom, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group  row">
            @*@Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Email</label>
            <div class="col-md-4">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
            <label class="control-label col-md-2">Giới tính</label>
            <div class="col-md-4">
                @Html.DropDownList("GioiTinh", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GioiTinh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group  row">
            <label class="control-label col-md-2">Ảnh đại diện</label>
            <div class="col-md-10">
                @if (File.Exists(Server.MapPath("/Content/images/avatars/avatar.png")))
                {
                    <img class="img-lg" title="avatar.png" alt="avatar.png" src="/Content/images/avatars/avatar.png" />
                    @Html.EditorFor(model => model.AnhDaiDien, new { htmlAttributes = new { @class = "form-control", @style = "display: none;" } })
                    <label for="photo">Chọn ảnh khác</label>
                    <input id="photo" type="file" name="photo" accept="image/x-png,image/jpeg,image/jpg" class="btn btn-warning" />
                    <input type="hidden" name="AnhDaiDien" value="avatar.png" />
                }
                else
                {
                    <label for="photo" class="control-label col-md-2">Đường dẫn</label>
                    <input id="photo" type="file" name="photo" accept="image/x-png,image/jpeg,image/jpg" class="btn btn-warning" />
                    <input type="hidden" name="AnhDaiDien" value="avatar.png" />
                }
            </div>
        </div>
        <div class="form-group  row">
            <label class="control-label col-md-2">Có hiệu lực</label>
            @*<div class="col-md-10 switch">
                @Html.CheckBoxFor(model => model.Active, htmlAttributes: new { @class = "form-control", @name = "Active", @checked = "checked" })
                <label for="Active"><i></i></label>
                @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
            </div>*@
            <div class="col-md-10">
                <div class="checkbox">
                    @{
                        bool Active = true;
                    }
                    @Html.CheckBoxFor(Model => Active, new Dictionary<string, object>() { { "checked", "true" }, { "data-off-color", "danger" }, { "class", "cbootstrapSwitch" } })
                    @Html.ValidationMessageFor(model => model.Active, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group  row">
            <div class="offset-md-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary" />
                <input type="button" value="Quay lại" class="btn btn-default" onclick="location.href='@Url.Action("Index")'" />
            </div>
        </div>
    </div>
}

<script>
    function DonViOnChange() {
        var maDV = $("#cbDonVi").val();
        $.ajax({
            url: '@Url.Action("DonViOnChange")',
            type: "GET",
            dataType: "JSON",
            data: { maDonVi: maDV },
            success: function (data) {
                $("#cbNhom").html(""); // clear before appending new list
                $.each(data, function (i, nhom) {
                    $("#cbNhom").append(
                        $('<option></option>').val(nhom.Id).html(nhom.Ten));
                })
            },
            error: function (xhr) {
                console.log("error: " + " status: " + status + " er:");
            }
        });

        $.ajax({
            url: '@Url.Action("DonViOnChangePhong")',
            type: "GET",
            dataType: "JSON",
            data: { maDonVi: maDV },
            success: function (data) {
                $("#cbPhong").html(""); // clear before appending new list
                $.each(data, function (i, nhom) {
                    $("#cbPhong").append(
                        $('<option></option>').val(nhom.Id).html(nhom.Ten));
                })
            },
            error: function (xhr) {
                console.log("error: " + " status: " + status + " er:");
            }
        });
    }
</script>

HopDongBanA/Views/HT_NguoiDung/Delete.cshtml
@model HopDongMgr.Models.HT_NguoiDung

@{
    ViewBag.Title = "Xóa người dùng";
}
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HT_NguoiDung</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaNguoiDung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaNguoiDung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhDaiDien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhDaiDien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DM_DONVI.TEN_DVIQLY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DM_DONVI.TEN_DVIQLY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HT_Nhom.Ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HT_Nhom.Ten)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HopDongBanA/Views/HT_NguoiDung/Details.cshtml
@model HopDongMgr.Models.HT_NguoiDung

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>HT_NguoiDung</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MaNguoiDung)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaNguoiDung)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MatKhau)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MatKhau)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoTen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoTen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AnhDaiDien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AnhDaiDien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DM_DONVI.TEN_DVIQLY)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DM_DONVI.TEN_DVIQLY)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HT_Nhom.Ten)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HT_Nhom.Ten)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.oid }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HopDongBanA/Views/HT_NguoiDung/Index.cshtml
@model IEnumerable<HopDongMgr.Models.HT_NguoiDung>

@{
    ViewBag.Title = "DANH SÁCH NGƯỜI DÙNG";
    ViewBag.ThongBaoXoa = "Bạn có chắc chắn muốn xóa người dùng này không?";
}

<div class="box-header">
    <input type="button" value="Thêm mới" class="btn btn-info" onclick="location.href='@Url.Action("Create")'" />
    <input type="button" value="Cập nhật" class="btn btn-warning" id="btnCapNhat" />
    <input type="button" value="Xóa" class="btn btn-danger" id="btnXoa" data-toggle="modal" data-target="#modal-danger" />
</div>
<div id="HHDC" class="table-scroll60">
    <table id="ListItem" class="table table-striped">
        <thead>
            <tr role="row" class="fixedHeader">
                <th>Mã người dùng</th>
                <th>Họ tên</th>
                <th>Giới tính</th>
                <th>Có hiệu lực</th>
                <th>Chức vụ</th>
                <th>Tên nhóm</th>
                <th>Tên phòng ban</th>
                <th>Tên đơn vị</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr role="row" id="@item.oid">
                    <td class="sorting_1">
                        @Html.DisplayFor(modelItem => item.MaNguoiDung)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HoTen)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.GioiTinh)
                    </td>
                    <td>
                        @Html.CheckBoxFor(modelItem => item.Active, new Dictionary<string, object>() { { "checked", "true" }, { "data-off-color", "danger" }, { "class", "cbootstrapSwitch" }, { "readonly", "readonly" } })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.HT_CHUCVU.Ten)
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.HT_Nhom.Ten)*@
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.DM_PHONG.Ten)*@
                    </td>
                    <td>
                        @*@Html.DisplayFor(modelItem => item.DM_DONVI.TEN_DVIQLY)*@
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>