HopDongBanA/Models/DM_HinhThucHopDong.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongMgr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HinhThucHopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DM_HinhThucHopDong()
        {
            this.CN_HopDong = new HashSet<CN_HopDong>();
        }
    
        public int IDHT { get; set; }
        public string TenHinhThuc { get; set; }
        public Nullable<bool> Khoa { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> DTXD_IDHinhThucHopDong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CN_HopDong> CN_HopDong { get; set; }
    }
}

HopDongBanA/Controllers/DM_HinhThucHopDongController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HopDongMgr.Models;
using HopDongMgr.Class.Common;
using HopDongMgr.DungChung;
using System.Data.SqlClient;
using X.PagedList;

namespace HopDongMgr.Controllers
{
    public class DM_HinhThucHopDongController : Controller
    {
        private HopDongMgrEntities db = new HopDongMgrEntities();
        private Common _common = new Common();
        private string ChucNang = "Danh mục hình thức hợp dồng";

        #region Lấy danh sách
        // GET: DM_HinhThucHopDong
        [CustomAuthorization]
        public ActionResult Index(int? page = 1)
        {
            db.Configuration.LazyLoadingEnabled = false;
            int pageIndex = (page < 1 ? 1 : page.Value);
            var pageSize = 10;
            int n = (pageIndex - 1) * pageSize;
            int totalData = db.DM_HinhThucHopDong.Count();
            List<DM_HinhThucHopDong> items = db.DM_HinhThucHopDong.OrderBy(p => p.TenHinhThuc).Skip(n).Take(pageSize).ToList();
            ViewBag.OnePageOfData = new StaticPagedList<DM_HinhThucHopDong>(items, pageIndex, pageSize, totalData);
            if (Request.IsAjaxRequest())
            {
                return PartialView("_IndexPartial");
            }
            return View();
        }

        // GET: DM_CongTrinh
        public ActionResult SeachIndex(string Seach = "", int? page = 1)
        {
            db.Configuration.LazyLoadingEnabled = false;
            int totalData;
            List<DM_HinhThucHopDong> items;
            int pageIndex = (page < 1 ? 1 : page.Value);
            var pageSize = 10;
            int n = (pageIndex - 1) * pageSize;
            if (string.IsNullOrEmpty(Seach))
            {
                TempData["Search"] = null;
                totalData = db.DM_HinhThucHopDong.Count();
                items = db.DM_HinhThucHopDong
                    .OrderBy(p => p.TenHinhThuc)
                    .Skip(n)
                    .Take(pageSize)
                    .ToList();
            }
            else
            {
                TempData["Search"] = Seach;
                totalData = db.DM_HinhThucHopDong
                            .Where(o => (o.TenHinhThuc.Contains(Seach) || Seach == ""))
                            .Count();
                items = db.DM_HinhThucHopDong
                            .Where(o => (o.TenHinhThuc.Contains(Seach) || Seach == ""))
                            .OrderBy(p => p.TenHinhThuc)
                            .Skip(n).Take(pageSize)
                            .ToList();

            }
            ViewBag.OnePageOfData = new StaticPagedList<DM_HinhThucHopDong>(items, pageIndex, pageSize, totalData);
            if (Request.IsAjaxRequest())
            {
                return PartialView("_IndexPartial");
            }
            return View("Index");
        }

        #endregion

        #region Create
        // GET: DM_HinhThucHopDong/Create
        [CustomAuthorization]
        public ActionResult Create()
        {
            return View();
        }

        // POST: DM_HinhThucHopDong/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDHT,TenHinhThuc,Khoa,NguoiTao,NgayTao,NguoiCapNhat,NgayCapNhat")] DM_HinhThucHopDong dM_HinhThucHopDong)
        {
            db.Configuration.LazyLoadingEnabled = false;
            try
            {
                if (ModelState.IsValid)
                {
                    List<SelectListItem> list = _common.getThongTinBang();
                    dM_HinhThucHopDong.NguoiTao = list.Where(o => o.Value == "NguoiTao").SingleOrDefault().Text;
                    dM_HinhThucHopDong.NgayTao = DateTime.Parse(list.Where(o => o.Value == "NgayTao").SingleOrDefault().Text);
                    db.DM_HinhThucHopDong.Add(dM_HinhThucHopDong);
                    db.SaveChanges();
                    HT_LichSuHoatDong ls = new HT_LichSuHoatDong(
                        ChucNang
                        , "CREATE"
                        , DateTime.Now, Session["username"]?.ToString()
                        , $" Thêm mới - Tên hình thức {dM_HinhThucHopDong.TenHinhThuc} ");
                    db.HT_LichSuHoatDong.Add(ls);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(dM_HinhThucHopDong);
            }
            catch (Exception ex)
            {
                string cauBaoLoi = "Không ghi được dữ liệu.<br/>Lý do: " + ex.Message;
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, cauBaoLoi);
            }
        }
        #endregion

        #region Update
        // GET: DM_HinhThucHopDong/Edit/5
        [CustomAuthorization]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            db.Configuration.LazyLoadingEnabled = false;
            DM_HinhThucHopDong dM_HinhThucHopDong = db.DM_HinhThucHopDong.Find(id);
            if (dM_HinhThucHopDong == null)
            {
                return HttpNotFound();
            }
            return View(dM_HinhThucHopDong);
        }

        // POST: DM_HinhThucHopDong/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDHT,TenHinhThuc,Khoa,NguoiTao,NgayTao,NguoiCapNhat,NgayCapNhat")] DM_HinhThucHopDong dM_HinhThucHopDong)
        {
            db.Configuration.LazyLoadingEnabled = false;
            try
            {
                //int d = db.DM_DongTien.Count(p => p.MaDongTien != dM_DongTien.MaDongTien && string.Compare(p.TenDongTien.Trim().Replace("\n", "").Replace("\r", ""), dM_DongTien.TenDongTien.Trim()) == 0);
                //if (d > 0) ModelState.AddModelError("TenDongTien", "Tên dồng tiền bị trùng.");
                if (ModelState.IsValid)
                {
                    List<SelectListItem> list = _common.getThongTinBang();
                    dM_HinhThucHopDong.NguoiCapNhat = list.Where(o => o.Value == "NguoiCapNhat").SingleOrDefault().Text;
                    dM_HinhThucHopDong.NgayCapNhat = DateTime.Parse(list.Where(o => o.Value == "NgayCapNhat").SingleOrDefault().Text);
                    db.Entry(dM_HinhThucHopDong).State = EntityState.Modified;
                    db.SaveChanges();
                    HT_LichSuHoatDong ls = new HT_LichSuHoatDong(
                        ChucNang
                        , "UPDATE"
                        , DateTime.Now, Session["username"]?.ToString()
                        , $" Cập nhật - Tên hình thức{dM_HinhThucHopDong.TenHinhThuc} ");
                    db.HT_LichSuHoatDong.Add(ls);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                return View(dM_HinhThucHopDong);
            }
            catch (Exception ex)
            {
                string cauBaoLoi = "Lỗi ghi dữ liệu.<br/>Lý do:" + ex.Message;
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, cauBaoLoi);
            }
        }

        #endregion

        #region Delete
        // POST: DM_HinhThucHopDong/Delete/5
        [HttpPost]
        [CustomAuthorization]
        public ActionResult Delete(int id)
        {
            DM_HinhThucHopDong dM_HinhThucHopDong = db.DM_HinhThucHopDong.Find(id);
            db.DM_HinhThucHopDong.Remove(dM_HinhThucHopDong);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        #endregion

        #region Dispose
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        #endregion

        #region DongBo
        [HttpPost]
        public ActionResult DongBo_DanhMucHinhThucHopDong()
        {
            string err = "";
            try
            {
                //string sqlQuery = "exec GetDTXD_DanhMucDiaDiem @Check OUTPUT";
                string sqlQuery = "EXEC @return_value = GetDTXD_DanhMucHinhThucHopDong";
                SqlParameter return_Pra = new SqlParameter("@return_value", SqlDbType.Int);
                return_Pra.Direction = ParameterDirection.Output;
                var i = db.Database.ExecuteSqlCommand(sqlQuery, return_Pra);
                int return_value = (int)return_Pra.Value;
                err = return_value.ToString(); // 1 thành công, 0 thất bại
            }
            catch (Exception ex)
            {
                err = "0"; // thất bại
            }

            return Json(err);
        }
        #endregion
    }
}

HopDongBanA/Views/DM_HinhThucHopDong/Create.cshtml
@model HopDongMgr.Models.DM_HinhThucHopDong

@{
    ViewBag.Title = "THÊM MỚI HÌNH THỨC HỢP ĐỒNG";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            @*@Html.LabelFor(model => model.TenHinhThuc, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Hình thức hợp đồng</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenHinhThuc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenHinhThuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @*@Html.LabelFor(model => model.Khoa, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Khóa</label>
            <div class="col-md-10">
                <div class="checkbox">
                    @{
                        bool Khoa = false;
                    }
                    @Html.CheckBoxFor(Model => Khoa, new Dictionary<string, object>() { { "checked", "true" }, { "data-off-color", "danger" }, { "class", "cbootstrapSwitch" } })
                    @Html.ValidationMessageFor(model => model.Khoa, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group row">
            <div class="offset-md-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary" />
                <input type="button" value="Quay lại" class="btn btn-default" onclick="location.href='@Url.Action("Index")'" />

            </div>
        </div>
    </div>
}

HopDongBanA/Views/DM_HinhThucHopDong/Delete.cshtml
@model HopDongMgr.Models.DM_HinhThucHopDong

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DM_HinhThucHopDong</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenHinhThuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenHinhThuc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Khoa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Khoa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NguoiTao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NguoiTao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayTao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayTao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NguoiCapNhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NguoiCapNhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayCapNhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HopDongBanA/Views/DM_HinhThucHopDong/Details.cshtml
@model HopDongMgr.Models.DM_HinhThucHopDong

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>DM_HinhThucHopDong</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TenHinhThuc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenHinhThuc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Khoa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Khoa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NguoiTao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NguoiTao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayTao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayTao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NguoiCapNhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NguoiCapNhat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayCapNhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.IDHT }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HopDongBanA/Views/DM_HinhThucHopDong/Edit.cshtml
@model HopDongMgr.Models.DM_HinhThucHopDong

@{
    ViewBag.Title = "CẬP NHẬT THÔNG TIN HÌNH THỨC HỢP ĐỒNG";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDHT)

        <div class="form-group row">
            @*@Html.LabelFor(model => model.TenHinhThuc, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Tên hình thức</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenHinhThuc, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenHinhThuc, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @*@Html.LabelFor(model => model.Khoa, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Khóa</label>
            <div class="col-md-10">
                <div class="checkbox">
                    @{
                        bool Khoa = Model.Khoa.GetValueOrDefault(false);
                    }
                    @Html.CheckBoxFor(Model => Khoa, new Dictionary<string, object>() { { "checked", "true" }, { "data-off-color", "danger" }, { "class", "cbootstrapSwitch" } })
                    @Html.ValidationMessageFor(model => model.Khoa, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group row">
            <div class="offset-md-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary" />
                <input type="button" value="Quay lại" class="btn btn-default" onclick="location.href='@Url.Action("Index")'" />
            </div>
        </div>
    </div>
}

HopDongBanA/Views/DM_HinhThucHopDong/Index.cshtml
@model IEnumerable<HopDongMgr.Models.DM_HinhThucHopDong>

@{
    ViewBag.Title = "DANH MỤC HÌNH THỨC HỢP ĐỒNG";
    ViewBag.ThongBaoXoa = "Bạn có chắc chắn muốn xóa hình thức hợp đồng này không?";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*toggel Đồng ý*@
<div class="modal modal-danger fade in" id="modal-danger-DongBo" style="display: none; padding-right: 17px;">
    <div class="modal-dialog modal-MD">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Thông báo</h4>
            </div>
            <div class="modal-body">
                <p>Đồng bộ danh mục Hình thức Hợp đồng từ chương trình ĐTXD</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Đóng</button>
                <button type="button" class="btn btn-outline" data-dismiss="modal" id="btnDongYDB">Đồng ý</button>
            </div>
        </div>
    </div>
</div>
@*---------*@
<div class="container px-0">
    <div class="row no-gutters">
        <div class="box-header col">
            <input type="button" value="Thêm mới" class="btn btn-info" onclick="location.href='@Url.Action("Create")'" />
            <input type="button" value="Cập nhật" class="btn btn-warning" id="btnCapNhat" />
            <input type="button" value="Xóa" class="btn btn-danger" id="btnXoa" data-toggle="modal" data-target="#modal-danger" />
            <input type="button" value="Đồng Bộ" class="btn" id="btnDongBo" data-toggle="modal" data-target="#modal-danger-DongBo" style="display:none" />

        </div>
    </div>
    @using (Ajax.BeginForm(
            "SeachIndex",
            //"Controler",
            ajaxOptions: new AjaxOptions
            {
                HttpMethod = "GET",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "DataUpdate"
            }))
    {
        <div class="row no-gutters">
            <div class="col-md-3 offset-md-9">
                <input class="form-control" type="text" name="Seach" id="Seach" placeholder="Tìm kiếm: Tên hình thức" />
            </div>
            <input id="submit" type="submit" hidden />
        </div>
    }
    <div id="DataUpdate" class=" container px-0 pt-1 form-horizontal">
        @Html.Partial("_IndexPartial")
    </div>
</div>

@section scripts
{
<script type="text/javascript">
    $(document).ready(function(){
        $('#btnDongYDB').click(function () {
                Loading();
                $.ajax({
                    url: "/DM_HinhThucHopDong/DongBo_DanhMucHinhThucHopDong",
                    dataType: "json",
                    type: "POST",
                    contentType: 'application/json; charset=utf-8',
                    async: true,
                    processData: false,
                    cache: false,
                    success: function (data) {
                        if (data == "1") {
                            LoadingHide();
                            $.notify({
                                title: '<strong>Thông báo</strong>:',
                                message: 'Đồng bộ thành công'
                            }, {
                                type: 'info'
                            });
                            var url = '@Url.Action("Index", "DM_HinhThucHopDong")';
                            window.location.href = url;
                        }
                        else {
                            $.notify({
                                title: '<strong>Thông báo</strong>:',
                                message: data + 'Có lỗi xảy ra khi đồng bộ'
                            }, {
                                type: 'danger'
                            });

                            console.log(data);
                            LoadingHide();
                        }
                    },
                    error: function (xhr) {
                        console.log("error: " + data + " status: " + status + " er:" + er);
                    }
                });

        });
        $('#Seach').keydown(function (event) {
            //alert(event.keyCode );
            if (event.keyCode == 27) {
                $('#Seach').val("");
                $('#submit').submit();
                return true;
            }
        });
    });
</script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
}

HopDongBanA/Views/DM_HinhThucHopDong/_IndexPartial.cshtml
@model DM_HinhThucHopDong
<div class="table-responsive row no-gutters">
    <table id="ListItem" class="table table-striped ">
        <thead>
            <tr role="row">
                <th>@Html.LabelFor(modelItem => Model.IDHT)</th>
                <th>@Html.LabelFor(modelItem => modelItem.TenHinhThuc)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (DM_HinhThucHopDong item in ViewBag.OnePageOfData)
            {
                <tr role="row" id="@item.IDHT">
                    <td>
                        @Html.DisplayFor(modelItem => item.IDHT)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TenHinhThuc)
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>
<div class="row container">
    @if (ViewBag.OnePageOfData != null)
    {
        string str = $"Trang {ViewBag.OnePageOfData.PageNumber} trên tổng số {ViewBag.OnePageOfData.PageCount} trang, {ViewBag.OnePageOfData.TotalItemCount} dòng";
        <div>@str</div>
    }
</div>
<div class="row">
    @if (TempData["Search"] == null) // gan them dieu kien khi sech bang rong
    {
        @Html.PagedListPager(
                                list: (IPagedList)ViewBag.OnePageOfData
                                , generatePageUrl: Page => Url.Action("Index", new { Page = Page })
                                , options: PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing
                                    (
                                        options: new PagedListRenderOptions
                                        {
                                            ContainerDivClasses = new string[] { "col", "dataTables_paginate ", "paging_simple_numbers" },
                                            UlElementClasses = new string[] { "pagination", "justify-content-end" },
                                            LiElementClasses = new string[] { "page-item" },
                                            PageClasses = new string[] { "page-link" },
                                        }
                                        , ajaxOptions: new AjaxOptions
                                        {
                                            UpdateTargetId = "DataUpdate",
                                            InsertionMode = InsertionMode.Replace,
                                            HttpMethod = "GET"
                                        }
                                    )
                            )

    }
    else
    {
        var Seach = TempData["Search"];
        @Html.PagedListPager(
                                list: (IPagedList)ViewBag.OnePageOfData
                                , generatePageUrl: Page => Url.Action("SeachIndex", new { Page = Page, Seach = Seach })
                                , options: PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing
                                    (
                                        options: new PagedListRenderOptions
                                        {
                                            ContainerDivClasses = new string[] { "col", "dataTables_paginate ", "paging_simple_numbers" },
                                            UlElementClasses = new string[] { "pagination", "justify-content-end" },
                                            LiElementClasses = new string[] { "page-item" },
                                            PageClasses = new string[] { "page-link" },
                                        }
                                        , ajaxOptions: new AjaxOptions
                                        {
                                            UpdateTargetId = "DataUpdate",
                                            InsertionMode = InsertionMode.Replace,
                                            HttpMethod = "GET"
                                        }
                                    )
                            )

    }

</div>