HopDongBanA/Models/CN_ThanhLy.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongMgr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CN_ThanhLy
    {
        public int IDTL { get; set; }
        public Nullable<int> IDHD { get; set; }
        public Nullable<bool> IsHoanThanh { get; set; }
        public Nullable<System.DateTime> NgayThanhLy { get; set; }
        public Nullable<decimal> GiaTriThanhLy { get; set; }
        public Nullable<decimal> GiaTriQuyetToan { get; set; }
        public Nullable<System.DateTime> NgayTongNghiemThu { get; set; }
        public string NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    
        public virtual CN_HopDong CN_HopDong { get; set; }
    }
}

HopDongBanA/Controllers/CN_ThanhLyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HopDongMgr.Models;
using HopDongMgr.Class.Common;
using HopDongMgr.DungChung;

namespace HopDongMgr.Controllers
{
    public class CN_ThanhLyController : Controller
    {
        private HopDongMgrEntities db = new HopDongMgrEntities();
        private Common _common = new Common();
        private string ChucNang = "Chức năng thanh lý hợp đồng";
        #region Lấy danh sách
        // GET: CN_ThanhLy
        [CustomAuthorization]
        public ActionResult Index()
        {
            var cN_ThanhLy = db.CN_ThanhLy.Include(c => c.CN_HopDong);
            return View(cN_ThanhLy.ToList());
        }

        #endregion

        #region Create
        //[CustomAuthorization]
        //public ActionResult Create()
        //{

        //        ViewBag.IDHD = new SelectList(db.CN_HopDong, "IDHD", "SoHopDong");       

        //    return View();
        //}

        // GET: CN_ThanhLy/Create
        [CustomAuthorization]
        public ActionResult Create(int? idhd)
        {
            int gIDHD;
            bool check = int.TryParse(idhd.ToString(), out gIDHD);
            if (!check)
            {
                ViewBag.IDHD = DanhSachHopDong();
            }
            else
            {
                ViewBag.IDHD = DanhSachHopDong(idhd.Value);
            }
            return View();
        }

        // POST: CN_ThanhLy/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDTL, IDHD, IsHoanThanh, NgayThanhLy, GiaTriThanhLy, GiaTriQuyetToan, NgayTongNghiemThu, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat")] CN_ThanhLy cN_ThanhLy)
        {
            try
            {
                db.Configuration.LazyLoadingEnabled = false;
                CN_ThanhLy newN_ThanhLy = db.CN_ThanhLy.Where(o => o.IDHD == cN_ThanhLy.IDHD).SingleOrDefault();
                CN_HopDong hopDong = db.CN_HopDong.Find(cN_ThanhLy.IDHD);
                if (cN_ThanhLy.NgayThanhLy < hopDong.NgayHetHan) ModelState.AddModelError("NgayThanhLy", $"Ngày thanh lý hợp đông nhỏ hơn Ngày hết hạn {hopDong.NgayHetHan}");

                if (ModelState.IsValid)
                {
                    List<SelectListItem> list = _common.getThongTinBang();
                    //CN_HopDong hopDong = db.CN_HopDong.Find(IDHD);
                    if (newN_ThanhLy == null)
                    {
                        cN_ThanhLy.NguoiTao = list.Where(o => o.Value == "NguoiTao").SingleOrDefault().Text;
                        cN_ThanhLy.NgayTao = DateTime.Parse(list.Where(o => o.Value == "NgayTao").SingleOrDefault().Text);
                        cN_ThanhLy.NguoiCapNhat = list.Where(o => o.Value == "NguoiCapNhat").SingleOrDefault().Text;
                        cN_ThanhLy.NgayCapNhat = DateTime.Parse(list.Where(o => o.Value == "NgayCapNhat").SingleOrDefault().Text);
                        db.CN_ThanhLy.Add(cN_ThanhLy);
                        db.SaveChanges();
                        #region luu lich su
                        // luu lich su
                        HT_LichSuHoatDong ls = new HT_LichSuHoatDong(
                            ChucNang
                            , "CREATE"
                            , DateTime.Now, Session["username"]?.ToString()
                            , $"Thêm mới - Thanh lý - số hợp đồng {hopDong?.SoHopDong} ");
                        db.HT_LichSuHoatDong.Add(ls);
                        db.SaveChanges();
                        #endregion
                    }
                    else
                    {
                        newN_ThanhLy.IDHD = cN_ThanhLy.IDHD;
                        newN_ThanhLy.IsHoanThanh = cN_ThanhLy.IsHoanThanh;
                        newN_ThanhLy.NgayThanhLy = cN_ThanhLy.NgayThanhLy;
                        newN_ThanhLy.GiaTriThanhLy = cN_ThanhLy.GiaTriThanhLy;
                        newN_ThanhLy.GiaTriQuyetToan = cN_ThanhLy.GiaTriQuyetToan;
                        newN_ThanhLy.NgayTongNghiemThu = cN_ThanhLy.NgayTongNghiemThu;
                        newN_ThanhLy.NguoiCapNhat = list.Where(o => o.Value == "NguoiCapNhat").SingleOrDefault().Text;
                        newN_ThanhLy.NgayCapNhat = DateTime.Parse(list.Where(o => o.Value == "NgayCapNhat").SingleOrDefault().Text);
                        db.Entry(newN_ThanhLy).State = EntityState.Modified;
                        db.SaveChanges();
                        #region luu lich su
                        // luu lich su
                        HT_LichSuHoatDong ls = new HT_LichSuHoatDong(
                        ChucNang
                        , "UPDATE"
                        , DateTime.Now, Session["username"]?.ToString()
                        , $"Cập nhật - Thanh lý - số hợp đồng { hopDong?.SoHopDong }");
                        db.HT_LichSuHoatDong.Add(ls);
                        db.SaveChanges();
                        #endregion
                    }
                    //TempData["err"] = "<div class='alert alert-success' role='alert'><span class='glyphicon glyphicon-exclamation - sign' aria-hidden='true'></span><span class='sr - only'></span>Cập nhật thành công</div> ";
                    return RedirectToAction("Index");
                }
                TempData["err"] = "<div class='alert alert-danger' role='alert'><span class='glyphicon glyphicon-exclamation - sign' aria-hidden='true'></span><span class='sr - only'></span>Có lỗi xảy ra</div> ";
                if (newN_ThanhLy == null)
                {
                    ViewBag.IDHD = DanhSachHopDong();
                }
                else
                {
                    ViewBag.IDHD = DanhSachHopDong(cN_ThanhLy.IDHD.Value);
                }
                return View(cN_ThanhLy);
            }
            catch (Exception ex)
            {
                string cauBaoLoi = "Không ghi được dữ liệu.<br/>Lý do: " + ex.Message;
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, cauBaoLoi);
            }
        }

        #endregion

        #region Edit

        // GET: CN_ThanhLy/Edit/5
        [CustomAuthorization]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CN_ThanhLy cN_ThanhLy = db.CN_ThanhLy.Find(id);
            if (cN_ThanhLy == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDHD = DanhSachHopDong(cN_ThanhLy.IDHD.Value);
            return View(cN_ThanhLy);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDTL, IDHD, IsHoanThanh, NgayThanhLy, GiaTriThanhLy, GiaTriQuyetToan, NgayTongNghiemThu, NguoiTao, NgayTao, NguoiCapNhat, NgayCapNhat")] CN_ThanhLy cN_ThanhLy, FormCollection fCollection)
        {
            try
            {
                db.Configuration.LazyLoadingEnabled = false;
                CN_HopDong hopDong = db.CN_HopDong.Find(cN_ThanhLy.IDHD);
                if (cN_ThanhLy.NgayThanhLy < hopDong.NgayHetHan) ModelState.AddModelError("NgayThanhLy", $"Ngày thanh lý hợp đổng nhỏ hơn Ngày hết hạn {hopDong.NgayHetHan}");
                if (ModelState.IsValid)
                {
                    List<SelectListItem> list = _common.getThongTinBang();
                    cN_ThanhLy.NguoiCapNhat = list.Where(o => o.Value == "NguoiCapNhat").SingleOrDefault().Text;
                    cN_ThanhLy.NgayCapNhat = DateTime.Parse(list.Where(o => o.Value == "NgayCapNhat").SingleOrDefault().Text);
                    db.Entry(cN_ThanhLy).State = EntityState.Modified;
                    db.SaveChanges();
                    //TempData["err"] = "<div class='alert alert-success' role='alert'><span class='glyphicon glyphicon-exclamation - sign' aria-hidden='true'></span><span class='sr - only'></span>Cập nhật thành công</div> ";
                    #region luu lich su
                    // luu lich su
                    HT_LichSuHoatDong ls = new HT_LichSuHoatDong(
                        ChucNang
                        , "UPDATE"
                        , DateTime.Now, Session["username"]?.ToString()
                        , $"Cập nhật - Thanh lý - số hợp đồng { hopDong?.SoHopDong }");
                    db.HT_LichSuHoatDong.Add(ls);
                    db.SaveChanges();
                    #endregion
                    return RedirectToAction("Index");
                }
                TempData["err"] = "<div class='alert alert-danger' role='alert'><span class='glyphicon glyphicon-exclamation - sign' aria-hidden='true'></span><span class='sr - only'></span>Có lỗi xảy ra</div> ";
                ViewBag.IDHD = DanhSachHopDong( cN_ThanhLy.IDHD.Value);
                return View(cN_ThanhLy);
            }
            catch (Exception ex)
            {
                string cauBaoLoi = "Không ghi được dữ liệu.<br/>Lý do: " + ex.Message;
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, cauBaoLoi);
            }
        }

        #endregion

        #region Delete
        // POST: CN_ThanhLy/Delete/5
        [HttpPost]
        [CustomAuthorization]
        public ActionResult Delete(int id)
        {
            CN_ThanhLy cN_ThanhLy = db.CN_ThanhLy.Find(id);
            db.CN_ThanhLy.Remove(cN_ThanhLy);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        #endregion

        #region Dispose
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

HopDongBanA/Views/CN_ThanhLy/Create.cshtml
@model HopDongMgr.Models.CN_ThanhLy

@{
    ViewBag.Title = "THANH LÝ HỢP ĐỒNG ";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //string dNgaycapNhat = DateTime.Now.ToString("dd/MM/yyyy");
}
<div>
    @Html.Raw(TempData["err"])
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            <label class="control-label col-md-2">Số hợp đồng</label>
            <div class="col-md-4">
                @Html.DropDownList("IDHD", null, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(model => model.IDHD, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">

            <label class="control-label col-md-2">Ngày tổng nghiệm thu</label>
            <div class="col-md-4">
                <div class="input-group date">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    @Html.TextBoxFor(model => model.NgayTongNghiemThu, "{0:dd/MM/yyyy}", new { @class = "form-control pull-right cDataPicker setDate", @placeholder = "DD/MM/YYYYY" })
                    @Html.ValidationMessageFor(model => model.NgayTongNghiemThu, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-9" id="errNgayKiemSoat"></div>
            </div>
            <label class="control-label col-md-2">Giá trị quyết toán</label>
            <div class="col-md-4">
                @Html.EditorFor(model => model.GiaTriQuyetToan, new { htmlAttributes = new { @class = "form-control CheckNumber" } })
                @Html.ValidationMessageFor(model => model.GiaTriQuyetToan, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            <label class="control-label col-md-2">Ngày thanh lý</label>
            <div class="col-md-4">
                <div class="input-group date">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    @Html.TextBoxFor(model => model.NgayThanhLy, "{0:dd/MM/yyyy}", new { @class = "form-control pull-right cDataPicker setDate", @placeholder = "DD/MM/YYYYY" })
                    @Html.ValidationMessageFor(model => model.NgayThanhLy, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-9" id="errNgayKiemSoat"></div>
            </div>
            <label class="control-label col-md-2">Giá trị thanh lý</label>
            <div class="col-md-4">
                @Html.EditorFor(model => model.GiaTriThanhLy, new { htmlAttributes = new { @class = "form-control CheckNumber " } })
                @Html.ValidationMessageFor(model => model.GiaTriThanhLy, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            <label class="control-label col-md-2">Trạng thái hoàn thành</label>
            <div class="col-md-4">
                <div class="checkbox">
                    @{
                        bool IsHoanThanh = false;
                    }
                    @Html.CheckBoxFor(Model => IsHoanThanh, new Dictionary<string, object>() { { "checked", "true" }, { "data-off-color", "danger" }, { "class", "cbootstrapSwitch" } })
                    @Html.ValidationMessageFor(model => model.IsHoanThanh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group row">
            <div class="offset-md-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary" />
                <input type="button" value="Quay lại" class="btn btn-default" onclick="location.href='@Url.Action("Index","CN_HopDong")'" />
            </div>
        </div>
    </div>
        @section  scripts
    {
            <script src="~/Scripts/App/CN_ThanhLyController/Creat_CN_ThanhLy.js"></script>
            <script>
            $(document).ready(function () {
            });
            </script>
        }
}

HopDongBanA/Views/CN_ThanhLy/Create_CN_ThanhLy.cshtml
@model HopDongMgr.Models.CN_ThanhLy

@{
    ViewBag.Title = "THANH LÝ HỢP ĐỒNG ";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //string dNgaycapNhat = DateTime.Now.ToString("dd/MM/yyyy");
}
<div>
    @Html.Raw(TempData["err"])
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @*@Html.LabelFor(model => model.IDHD, "IDHD", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-3">Số hợp đồng</label>
            <div class="col-md-7">
                @Html.DropDownList("IDHD", null, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(model => model.IDHD, "", new { @class = "text-danger" })
            </div>
            @*@Html.LabelFor(model => model.NgayThanhLy, htmlAttributes: new { @class = "control-label col-md-2" })*@
        </div>
        <div class="form-group">
            
            <label class="control-label col-md-3">Ngày tổng nghiệm thu</label>
            <div class="col-md-2">
                <div class="input-group date">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    @Html.TextBoxFor(model => model.NgayTongNghiemThu, "{0:dd/MM/yyyy}", new { @class = "form-control pull-right cDataPicker setDate", @placeholder = "DD/MM/YYYYY" })
                    @Html.ValidationMessageFor(model => model.NgayTongNghiemThu, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-9" id="errNgayKiemSoat"></div>
            </div>     
            
            <label class="control-label col-md-2">Giá trị quyết toán</label>
            <div class="col-md-3">
                <input class="form-control CheckNumber Number-Get-GTQT" value="" />
                @Html.EditorFor(model => model.GiaTriQuyetToan, new { htmlAttributes = new { @class = "form-control Number-Set-GTQT", @type = "Hidden" } })
                @Html.ValidationMessageFor(model => model.GiaTriQuyetToan, "", new { @class = "text-danger" })
            </div>       
        </div>
        <div class="form-group">
            <label class="control-label col-md-3">Ngày thanh lý</label>
            <div class="col-md-2">
                <div class="input-group date">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    @Html.TextBoxFor(model => model.NgayThanhLy, "{0:dd/MM/yyyy}", new { @class = "form-control pull-right cDataPicker setDate", @placeholder = "DD/MM/YYYYY" })
                    @Html.ValidationMessageFor(model => model.NgayThanhLy, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-9" id="errNgayKiemSoat"></div>
            </div>
            <label class="control-label col-md-2">Giá trị thanh lý</label>
            <div class="col-md-3">
                <input class="form-control CheckNumber Number-Get-GTTL" value="" />
                @Html.EditorFor(model => model.GiaTriThanhLy, new { htmlAttributes = new { @class = "form-control Number-Set-GTTL", @type = "Hidden" } })
                @Html.ValidationMessageFor(model => model.GiaTriThanhLy, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-3">Trạng thái hoàn thành</label>
            <div class="col-md-3">
                <div class="checkbox">
                    @Html.CheckBox("IsHoanThanh", new Dictionary<string, object>() { { "checked", "true" }, { "data-off-color", "danger" }, { "class", "cbootstrapSwitch" } })
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-3 col-md-10">
                @*<input type="submit" value="Lưu" class="btn btn-info" />*@
                <input type="button" value="Lưu" class="btn btn-primary" id="btnThemThanhLy" />
                <input type="button" value="Quay lại" class="btn btn-default" onclick="location.href='@Url.Action("Index","CN_HopDong")'" />
            </div>
        </div>
        </div>
    @section  scripts
    {
        <script src="~/Scripts/App/CN_ThanhLyController/Creat_CN_ThanhLy.js"></script>
        <script>
            $(document).ready(function () {
                $(".Number-Get-GTQT").focusout(function () {
                    var val = $(this).val().replace(/,/g,"");
                    $(".Number-Set-GTQT").val(val);
                });
                $(".Number-Get-GTTL").focusout(function () {
                    var val = $(this).val().replace(/,/g, "");
                    $(".Number-Set-GTTL").val(val);
                });

                @*$(".setDate").val("@dNgaycapNhat");*@
            });
        </script>
    }
}

HopDongBanA/Views/CN_ThanhLy/Edit.cshtml
@model HopDongMgr.Models.CN_ThanhLy

@{
    ViewBag.Title = "THANH LÝ HỢP ĐỒNG";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string sGiatriQT = Model.GiaTriQuyetToan.HasValue == false ? "0" : string.Format("{0:0,0}", Model.GiaTriQuyetToan.Value);
    string sGiatriTL = Model.GiaTriThanhLy.HasValue == false ? "0" : string.Format("{0:0,0}", Model.GiaTriThanhLy.Value);
}
<div>
    @Html.Raw(TempData["err"])
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.IDTL)
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            @*@Html.LabelFor(model => model.IDHD, "IDHD", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Số hợp đồng</label>
            <div class="col-md-4">
                @Html.DropDownList("IDHD", null, htmlAttributes: new { @class = "form-control", @readonly = "readonly" })
                @Html.ValidationMessageFor(model => model.IDHD, "", new { @class = "text-danger" })
            </div>
            @*@Html.LabelFor(model => model.NgayThanhLy, htmlAttributes: new { @class = "control-label col-md-2" })*@
        </div>
        <div class="form-group row">

            <label class="control-label col-md-2">Ngày tổng nghiệm thu</label>
            <div class="col-md-4">
                <div class="input-group date">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    @Html.TextBoxFor(model => model.NgayTongNghiemThu, "{0:dd/MM/yyyy}", new { @class = "form-control pull-right cDataPicker setDate", @placeholder = "DD/MM/YYYYY" })
                    @Html.ValidationMessageFor(model => model.NgayTongNghiemThu, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-9" id="errNgayKiemSoat"></div>
            </div>

            <label class="control-label col-md-2">Giá trị quyết toán</label>
            <div class="col-md-4">
                <input class="form-control CheckNumber Number-Get-GTQT" value="@sGiatriQT" />
                @Html.EditorFor(model => model.GiaTriQuyetToan, new { htmlAttributes = new { @class = "form-control Number-Set-GTQT", @type = "Hidden" } })
                @Html.ValidationMessageFor(model => model.GiaTriQuyetToan, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            <label class="control-label col-md-2">Ngày thanh lý</label>
            <div class="col-md-4">
                <div class="input-group date">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    @Html.TextBoxFor(model => model.NgayThanhLy, "{0:dd/MM/yyyy}", new { @class = "form-control pull-right cDataPicker setDate", @placeholder = "DD/MM/YYYYY" })
                    @Html.ValidationMessageFor(model => model.NgayThanhLy, "", new { @class = "text-danger" })
                </div>
                <div class="col-sm-9" id="errNgayKiemSoat"></div>
            </div>
            <label class="control-label col-md-2">Giá trị thanh lý</label>
            <div class="col-md-4">
                <input class="form-control CheckNumber Number-Get-GTTL" value="@sGiatriTL" />
                @Html.EditorFor(model => model.GiaTriThanhLy, new { htmlAttributes = new { @class = "form-control Number-Set-GTTL", @type = "Hidden" } })
                @Html.ValidationMessageFor(model => model.GiaTriThanhLy, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            <label class="control-label col-md-2">Trạng thái hoàn thành</label>
            <div class="col-md-4">
                <div class="checkbox">
                    @{
                        bool IsHoanThanh = Model.IsHoanThanh.GetValueOrDefault(false);
                    }
                    @Html.CheckBoxFor(Model => IsHoanThanh, new Dictionary<string, object>() { { "checked", "true" }, { "data-off-color", "danger" }, { "class", "cbootstrapSwitch" } })
                    @Html.ValidationMessageFor(model => model.IsHoanThanh, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group row">
            <div class="offset-md-2 col-md-10">
                <input type = "submit" value="Lưu" class="btn btn-primary" />
                @*<input type="button" value="Lưu" class="btn btn-primary" id="btnThemThanhLy" />*@
                <input type="button" value="Quay lại" class="btn btn-default" onclick="location.href='@Url.Action("Index", "CN_ThanhLy")'" />
            </div>
        </div>
    </div>

    @section scripts
    {
        <script>
            $(document).ready(function () {
                $(".Number-Get-GTQT").focusout(function () {
                    var val = $(this).val().replace(/,/g,"");
                    $(".Number-Set-GTQT").val(val);
                });
                $(".Number-Get-GTTL").focusout(function () {
                    var val = $(this).val().replace(/,/g, "");
                    $(".Number-Set-GTTL").val(val);
                });
            });

            $('#btnXoaTL').click(function () {
                var idSelected = $("#IDTL").attr("id");
                if (idSelected != undefined) {
                    Loading();
                    $.ajax({
                        method: 'POST',
                        url: '@Url.Action("Delete", "CN_ThanhLy")',
                        data: { id: idSelected },
                        success: function (data) {
                            LoadingHide();

                            $.notify({
                                // options
                                message: 'Xóa thành công'
                            }, {
                                // settings
                                type: 'info'
                            });
                        },
                        error: function (data) {
                            $.notify({
                                // options
                                message: 'Có lỗi xảy ra.'
                            }, {
                                // settings
                                type: 'Danger'
                            });
                        }

                    })
                }
                
            });
        </script>
    }
}