HopDongBanA/Models/CN_HopDong.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HopDongMgr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CN_HopDong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CN_HopDong()
        {
            this.CN_DieuChinh = new HashSet<CN_DieuChinh>();
            this.CN_ThanhLy = new HashSet<CN_ThanhLy>();
        }
    
        public int IDHD { get; set; }
        public Nullable<int> IDLoai { get; set; }
        public string MaCT { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> NamGiaoA { get; set; }
        public Nullable<int> IDDV { get; set; }
        public Nullable<decimal> GiaTriGoiThau { get; set; }
        public Nullable<int> IDHT { get; set; }
        public string SoHopDong { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public Nullable<decimal> GiaTriHopDong { get; set; }
        public Nullable<int> SoNgayThucHien { get; set; }
        public Nullable<int> SoNgayThiCong { get; set; }
        public string XuLyViPham { get; set; }
        public Nullable<decimal> GiaTriPhat { get; set; }
        public string XuLyTranhChap { get; set; }
        public Nullable<System.Guid> NguoiTao { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string NguoiCapNhat { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<decimal> DTXD_IDHopDong { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public Nullable<decimal> IDCT { get; set; }
        public Nullable<decimal> GiaTriThucTe { get; set; }
        public Nullable<System.DateTime> NgayHetHanThucTe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CN_DieuChinh> CN_DieuChinh { get; set; }
        public virtual CN_HopDong CN_HopDong1 { get; set; }
        public virtual CN_HopDong CN_HopDong2 { get; set; }
        public virtual DM_CongTrinh DM_CongTrinh { get; set; }
        public virtual DM_DonViThucHien DM_DonViThucHien { get; set; }
        public virtual DM_HinhThucHopDong DM_HinhThucHopDong { get; set; }
        public virtual DM_LoaiHopDong DM_LoaiHopDong { get; set; }
        public virtual HT_NguoiDung HT_NguoiDung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CN_ThanhLy> CN_ThanhLy { get; set; }
    }
}

HopDongBanA/Controllers/CN_HopDongController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HopDongMgr.Models;
using HopDongMgr.Class.Common;
using HopDongMgr.DungChung;
using System.Linq.Dynamic;
using System.Data.SqlClient;
using System.Linq.Expressions;
using X.PagedList;

namespace HopDongMgr.Controllers
{
    public class CN_HopDongController : Controller
    {
        private HopDongMgrEntities db = new HopDongMgrEntities();
        private Common _common = new Common();
        private string ChucNang = "Chức năng hợp đồng";

        #region lấy danh sách 
        // GET: CN_HopDong
        [CustomAuthorization]
        public ActionResult Index(string SoHopDong = "", string TenCT = "", decimal? NamGiaoAtest = -1,  int? NamGiaoA = -1, int? IsHoanThanh = -1, int? page = 1)
        {
            decimal rrrrr = -1;
            //SoHopDong TenCT NamGiaoA IsHoanThanh
            db.Configuration.LazyLoadingEnabled = false;
            int totalData;
            IQueryable<CN_HopDong> itemsQuery = db.CN_HopDong
                        .Include(d => d.DM_CongTrinh)
                        .Include(d => d.DM_DonViThucHien)
                        .Include(d => d.DM_HinhThucHopDong)
                        .Include(d => d.CN_ThanhLy)
                        .Include(d => d.DM_LoaiHopDong).AsQueryable();

            if (!string.IsNullOrEmpty(SoHopDong) && !string.IsNullOrWhiteSpace(SoHopDong))
            {
                itemsQuery = itemsQuery.Where(o => o.SoHopDong.Contains(SoHopDong.Trim()));
                TempData["SoHopDong"] = SoHopDong;
            }
            if (!string.IsNullOrEmpty(TenCT) && !string.IsNullOrWhiteSpace(TenCT))
            {
                itemsQuery = itemsQuery.Where(o => o.DM_CongTrinh.TenCT.Contains(TenCT.Trim()));
                TempData["TenCT"] = TenCT;
            }
            if (NamGiaoA > -1)
            {
                itemsQuery = itemsQuery.Where(o => o.NamGiaoA == NamGiaoA);
                TempData["NamGiaoA"] = NamGiaoA;
            }
            if (IsHoanThanh > -1)
            {
                bool check = Convert.ToBoolean(IsHoanThanh);
                itemsQuery = itemsQuery.Where(o => o.CN_ThanhLy.Where(oo => o.IDHD == oo.IDHD).FirstOrDefault().IsHoanThanh == check);
                TempData["IsHoanThanh"] = IsHoanThanh;
            }

            List<CN_HopDong> items;
            int pageIndex = (page < 1 ? 1 : page.Value);
            var pageSize = 10;
            int n = (pageIndex - 1) * pageSize;

            totalData = itemsQuery.Count();
            items = itemsQuery
                    .OrderByDescending(p => p.NgayKy)
                    .Skip(n)
                    .Take(pageSize)
                    .ToList();

            ViewBag.OnePageOfData = new StaticPagedList<CN_HopDong>(items, pageIndex, pageSize, totalData);
            if (Request.IsAjaxRequest())
            {
                return PartialView("_IndexPartial");
            }
            return View("Index");
        }
        
        public ActionResult Index_HetHanDieuChinh()
        {
            if (Session["userid"] != null)
            {
                Guid IDNguoiDung = (Guid)Session["userid"];
                return View(db.GetList_HopDongHetHan(IDNguoiDung, DateTime.Now.Date, -1).ToList());
            }
            else
                return RedirectToAction("Login", "Home");
        }

        public ActionResult _Index_HetHanDieuChinhPartial()
        {
            if (Session["userid"] != null)
            {
                Guid IDNguoiDung = (Guid)Session["userid"];
                return View(db.GetList_HopDongHetHan(IDNguoiDung, DateTime.Now.Date, -1).ToList());
            }
            else
                return RedirectToAction("Login", "Home");
        }

        public ActionResult Index_DanhSachHopDongHetHan()
        {
            try
            {
                Guid IDNguoiDung = (Guid)Session["userid"];
                List<List<GetList_HopDongHetHan_ALL_Model>> List = new List<List<GetList_HopDongHetHan_ALL_Model>>();

                object[] listParaDC = {
                    new SqlParameter { ParameterName = "idNguoiDung", SqlDbType = SqlDbType.UniqueIdentifier, Value = IDNguoiDung },
                    new SqlParameter { ParameterName = "pNgay", SqlDbType = SqlDbType.Date, Value = DateTime.Now.Date },
                    new SqlParameter { ParameterName = "pSoNgay", SqlDbType = SqlDbType.Int, Value = "1" },
                    new SqlParameter { ParameterName = "pLoai", SqlDbType = SqlDbType.VarChar, Value = "DC" } // điều chỉnh
                };
                List<GetList_HopDongHetHan_ALL_Model> lHDHetHanDC = db.Database.SqlQuery<GetList_HopDongHetHan_ALL_Model>($"EXEC [dbo].[GetList_HopDongHetHan_ALL] @idNguoiDung, @pNgay , @pSoNgay, @pLoai ", listParaDC).ToList();
                List.Insert(0, lHDHetHanDC);

                object[] listParaTC = {
                    new SqlParameter { ParameterName = "idNguoiDung", SqlDbType = SqlDbType.UniqueIdentifier, Value = IDNguoiDung },
                    new SqlParameter { ParameterName = "pNgay", SqlDbType = SqlDbType.Date, Value = DateTime.Now.Date },
                    new SqlParameter { ParameterName = "pSoNgay", SqlDbType = SqlDbType.Int, Value = "1" },
                    new SqlParameter { ParameterName = "pLoai", SqlDbType = SqlDbType.VarChar, Value = "TC" } // thi công
                };
                List<GetList_HopDongHetHan_ALL_Model> lHDHetHanTC = db.Database.SqlQuery<GetList_HopDongHetHan_ALL_Model>($"EXEC [dbo].[GetList_HopDongHetHan_ALL] @idNguoiDung, @pNgay , @pSoNgay, @pLoai ", listParaTC).ToList();
                List.Insert(1, lHDHetHanTC);

                object[] listParaTH = {
                    new SqlParameter { ParameterName = "idNguoiDung", SqlDbType = SqlDbType.UniqueIdentifier, Value = IDNguoiDung },
                    new SqlParameter { ParameterName = "pNgay", SqlDbType = SqlDbType.Date, Value = DateTime.Now.Date },
                    new SqlParameter { ParameterName = "pSoNgay", SqlDbType = SqlDbType.Int, Value = "1" },
                    new SqlParameter { ParameterName = "pLoai", SqlDbType = SqlDbType.VarChar, Value = "TH" } // thực hiện
                };
                List<GetList_HopDongHetHan_ALL_Model> lHDHetHanTH = db.Database.SqlQuery<GetList_HopDongHetHan_ALL_Model>($"EXEC [dbo].[GetList_HopDongHetHan_ALL] @idNguoiDung, @pNgay , @pSoNgay, @pLoai ", listParaTH).ToList();
                List.Insert(2, lHDHetHanTH);


                return View(model: List);
            }
            catch (Exception ex)
            {
                return View();
            }

        }

        [HttpPost]
        public ActionResult GetList_HetHanDieuChinh()
        {
            #region
            if (Session["userid"] != null)
            {
                Guid IDNguoiDung = (Guid)Session["userid"];
                return View(db.GetList_HopDongHetHan(IDNguoiDung, DateTime.Now.Date, 20).ToList());
            }
            else
                return RedirectToAction("Login", "Home");
            #endregion
            //int start = Convert.ToInt32(Request["start"]);
            //int length = Convert.ToInt32(Request["length"]);
            //string searchVale = Request["search[Value]"];
            //string sorColumnName = Request["columns[" + Request["order[0][column]"] + "][name]"];
            //string sortDirection = Request["order[0][dir]"];


            //if (Session["userid"] != null)
            //{
            //    Guid IDNguoiDung = (Guid)Session["userid"];
            //    List<oCN_HopDong> list = new List<oCN_HopDong>();
            //    list = db.GetList_HopDongHetHan(IDNguoiDung, DateTime.Now.Date, 20).Select(x => new oCN_HopDong
            //    {
            //        DT_RowId = x.IDHD
            //        ,
            //        TenCT = x.DM_CongTrinh == null ? "-" : x.DM_CongTrinh.TenCT
            //        ,
            //        SoHD = x.SoHopDong
            //        ,
            //        NgayKy = x.NgayKy.Value.ToString() //x.NgayKy.Value.ToString("dd/MM/yyyy")//string.Format("{0}",string.Format("{0:dd-MM-yyyy}", x.NgayKy.Value))//x.NgayKy.HasValue == true ? x.NgayKy.Value.ToLongDateString(): "-"
            //        ,
            //        GiaTriHopDong = x.GiaTriHopDong.ToString()//string.Format("{0:0,0}", x.GiaTriHopDong.Value) // x.GiaTriHopDong
            //        ,
            //        SoNgayThucHien = x.SoNgayThucHien.ToString()
            //        ,
            //        SoNgayThiCong = x.SoNgayThiCong.ToString()
            //        ,
            //        NamGiaoA = x.NamGiaoA
            //        ,
            //        TenDVTH = string.IsNullOrEmpty(x.DM_DonViThucHien.TenDV) ? "-" : x.DM_DonViThucHien.TenDV
            //        ,
            //        GiaTriGoiThau = x.GiaTriGoiThau.ToString()
            //        ,
            //        TenHTHD = string.IsNullOrEmpty(x.DM_HinhThucHopDong.TenHinhThuc) ? "-" : x.DM_HinhThucHopDong.TenHinhThuc
            //        ,
            //        NoiDung = x.NoiDung
            //        ,
            //        NguoiTheoDoi = x.NguoiTao
            //        ,
            //        NgayCapNhat = x.NgayCapNhat

            //    }).ToList();
            //    int TotalRecord = list.Count;
            //    if (!string.IsNullOrEmpty(searchVale))
            //    {
            //        list = list.Where(x => x.SoHD.ToLower().Contains(searchVale.ToLower())
            //        || x.TenCT.ToLower().Contains(searchVale.ToLower())
            //        ).ToList();
            //    }
            //    int totalrowFiter = list.Count;
            //    list = list.OrderBy(sorColumnName + " " + sortDirection).ToList();
            //    list = list.Skip(start).Take(length).ToList();

HopDongBanA/Views/CN_HopDong/Edit_XuPhatTranhChap.cshtml
@model HopDongMgr.Models.CN_HopDong

@{
    ViewBag.Title = "CẬP NHẬT THÔNG TIN TRANH CHẤP";
    Layout = "~/Views/Shared/_Layout.cshtml";
    string sGTP = Model.GiaTriPhat.HasValue == false ? "0" : string.Format("{0:0,0}", Model.GiaTriPhat.Value);

}
<div>
    @Html.Raw(TempData["err"])
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDHD)

        <div class="form-group row">
            @*@Html.LabelFor(model => model.SoHopDong, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Số hợp đồng</label>
            <div class="col-md-4">
                @Html.EditorFor(model => model.SoHopDong, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.SoHopDong, "", new { @class = "text-danger" })
            </div>
            @*@Html.LabelFor(model => model.SoHopDong, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Giá trị phạt <span style="color:red">(*)</span></label>
            <div class="col-md-4">
                @Html.EditorFor(model => model.GiaTriPhat, new { htmlAttributes = new { @class = "form-control CheckNumber"} })
                @Html.ValidationMessageFor(model => model.GiaTriPhat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            @*@Html.LabelFor(model => model.NoiDung, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Xử lý vi phạm</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.XuLyViPham, new { @class = "form-control", rows = "3" })
                @Html.ValidationMessageFor(model => model.XuLyViPham, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            @*@Html.LabelFor(model => model.NoiDung, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <label class="control-label col-md-2">Xử lý tranh chấp</label>
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.XuLyTranhChap, new { @class = "form-control", rows = "3" })
                @Html.ValidationMessageFor(model => model.XuLyTranhChap, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="offset-md-2 col-md-10">
                <input type="submit" value="Lưu" class="btn btn-primary" />
                <input type="button" value="Quay lại" class="btn btn-default" onclick="location.href='@Url.Action("Index")'" />
            </div>
        </div>
    </div>

    @section scripts
    {
        <script>
            $(document).ready(function () {
                $(".Number-Get-GTP").focusout(function () {
                    var val = $(this).val().replace(/,/g,"");
                    $(".Number-Set-GTP").val(val);
                });
            });
        </script>
    }
}

HopDongBanA/Views/CN_HopDong/Index - Copy.cshtml
@model IEnumerable<HopDongMgr.Models.CN_HopDong>

@{
    ViewBag.Title = "DANH SÁCH HỢP ĐỒNG";
    ViewBag.ThongBaoXoa = "Bạn có chắc chắn muốn xóa hợp đồng này không?";
}
<link href="~/Content/dataTables.1.10.16/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
<link href="~/Content/dataTables.1.10.16/dataTables.semanticui.min.css" rel="stylesheet" type="text/css">
<link href="~/Content/bootstrap-toggle.min.css" rel="stylesheet" type="text/css">
<link href="~/Content/dataTables.Ajax.semantic-ui/dataTables.semanticui.min.css" rel="stylesheet" type="text/css">
<link href="~/Content/dataTables.1.10.16.Responsive.semanticui/responsive.semanticui.min.css" rel="stylesheet" type="text/css">
@*<link href="https://cdn.datatables.net/1.10.16/css/dataTables.semanticui.min.css" rel="stylesheet" type="text/css">*@
@*<link href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.0/semantic.min.css" rel="stylesheet" type="text/css">*@
<link href="~/Content/dataTables.semantic-ui.2.3.0/semantic.min.css" rel="stylesheet" type="text/css">

@*toggel Đồng ý*@
<div class="modal modal-danger fade in" id="modal-danger-DongBo" style="display: none; padding-right: 17px;">
    <div class="modal-dialog modal-MD">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Thông báo</h4>
            </div>
            <div class="modal-body">
                <p>Đồng bộ danh mục Hợp đồng từ chương trình ĐTXD</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">Đóng</button>
                <button type="button" class="btn btn-outline" data-dismiss="modal" id="btnDongYDB">Đồng ý</button>
            </div>
        </div>
    </div>
</div>
@*---------*@
<div class="box-header">
    <input type="button" value="Thêm mới" class="btn btn-info" onclick="location.href='@Url.Action("Create")'" />
    <input type="button" value="Cập nhật" class="btn btn-warning" id="btnCapNhat" />
    <input type="button" value="Xóa" class="btn btn-danger" id="btnXoa" data-toggle="modal" data-target="#modal-danger" />
    <input type="button" value="Thanh lý" class="btn btn-default" onclick="" id="btnThanhLy" />
    <input type="button" value="Xử phạt" class="btn btn-navy" onclick="" id="btnXuPhat" />
    <input type="button" value="Hết hạn điều chỉnh" class="btn btn-danger" onclick="" id="btnHetHan" />
    <input type="button" value="Đồng Bộ" class="btn" id="btnDongBo" data-toggle="modal" data-target="#modal-danger-DongBo" />

</div>

@*<table id="example" class="display nowrap dataTable dtr-inline" cellspacing="0" role="grid" aria-describedby="example_info" style="width: 100%;">*@
<table id="example" class="ui celled table responsive nowrap display nowrap dataTable dtr-inline" role="grid" aria-describedby="example_info" style="width:100%">
    <thead>
        <tr role="row">
            <th>Công trình</th>
            <th>Số hợp đồng</th>
            <th>Ngày ký</th>
            <th>Giá trị hợp đồng</th>
            <th>Giá trị gói thầu</th>
            <th>Số ngày thực hiện</th>
            <th>Số ngày thi công</th>
            <th>Năm giao A</th>
            <th>Đơn vị thực hiện</th>
            <th>Hình thức hợp đồng</th>
            <th>Nội dung</th>
            <th>Người theo dõi</th>
            <th>Ngày cập nhật</th>
        </tr>
    </thead>
    <tfoot>
        <tr role="row">
            <th>Công trình</th>
            <th>Số hợp đồng</th>
            <th>Ngày ký</th>
            <th>Giá trị hợp đồng</th>
            <th>Giá trị gói thầu</th>
            <th>Số ngày thực hiện</th>
            <th>Số ngày thi công</th>
            <th>Năm giao A</th>
            <th>Đơn vị thực hiện</th>
            <th>Hình thức hợp đồng</th>
            <th>Nội dung</th>
            <th>Người theo dõi</th>
            <th>Ngày cập nhật</th>
        </tr>
    </tfoot>

</table>
@section scripts
    {
    <script src="~/Scripts/jquery-1.12.4.js"></script>
    <script src="~/Scripts/DataTables/jquery.dataTables.1.10.16/jquery.dataTables.min.js"></script>
    <script src="~/Scripts/DataTables/jquery.dataTables.1.10.16/dataTables.semanticui.min.js"></script>
    <script src="~/Scripts/DataTables/responsive.2.2.1/dataTables.responsive.min.js"></script>
    <script src="~/Scripts/DataTables/responsive.2.2.1/responsive.semanticui.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            //#region processing-side
            $("#example").DataTable({
                responsive: true,
                "ajax": {
                    "url": "@Url.Action("GetList", "CN_HopDong")",
                "type": "POST",
                "datatype": "json"
            },
                columns: [
                    { "data": "TenCT", "name": "TenCT", },
                    { "data": "SoHD", "name": "SoHD" },
                    { "data": "NgayKy", "name": "NgayKy" },
                    { "data": "GiaTriHopDong", "name": "GiaTriHopDong" },
                    { "data": "GiaTriGoiThau", "name": "GiaTriGoiThau" }, // giá trị gói thầu
                    { "data": "SoNgayThucHien", "name": "SoNgayThucHien" },
                    { "data": "SoNgayThiCong", "name": "SoNgayThiCong" },
                    { "data": "NamGiaoA", "name": "NamGiaoA" },
                    { "data": "TenDVTH", "name": "TenDVTH" },
                    { "data": "TenHTHD", "name": "TenHTHD" },
                    { "data": "NoiDung", "name": "NoiDung" },
                    { "data": "NguoiTheoDoi", "name": "NguoiTheoDoi" },
                    { "data": "NgayCapNhat", "name": "NgayCapNhat" },
                ],
                "columnDefs": [
                    {
                        "targets": 2,
                        "className": "dt-right",
                    }
                    , {
                        "targets": 3,
                        "className": "dt-right",
                    }
                    , {
                        "targets": 4,
                        "className": "dt-right",
                    }
                    , {
                        "targets": 5,
                        "className": "dt-right",
                    }
                    , {
                        "targets": 6,
                        "className": "dt-right",
                    }

                ],
                "fnDrawCallback": function() {
                    //$('#example tbody .khoa').bootstrapToggle({
                    //});
                },
            responsive: {
                details: {
                        renderer: function ( api, rowIdx, columns ) {
                            var data = $.map(columns, function (col, i) {
                                var string;
                                if (col.title == "Nội dung")
                                {
                                    _string =   '<tr data-dt-row="' + col.rowIndex + '" data-dt-column="' + col.columnIndex + '">' +
                                                '<td>' + col.title + ':' + '</td> ' +
                                                '<td> <textarea rows="4" cols="50"> ' + col.data + '</textarea> </td>' +
                                                '</tr>'
                                }
                                else
                                {
                                    _string =  '<tr data-dt-row="'+col.rowIndex+'" data-dt-column="'+col.columnIndex+'">'+
                                        '<td>' + col.title+':'+'</td> '+
                                        '<td>' + col.data + '</td>' +
                                        '</tr>'
                                }
                                return col.hidden ?
                                    _string:
                                    '';
                            } ).join('');

                            return data ?
                                $('<table/>').append( data ) :
                                false;
                        }
                }
            },
            "serverSide": "true",
            "order": [0, "asc"],
            "processing": "true",
            "language": {
                "processing": "processing ..... please"
            }

        });

        $('#example tbody').on('click', 'tr', function () {

            $('#example tbody tr').removeClass("selected");
            $(this).toggleClass("selected");
        });
//#endregion processing-side


            $('#btnThanhLy').click(function () {
                var idSelected = $("#example .selected").attr("id");
                if (idSelected != undefined) {
                        var url = '@Url.Action("Create_CN_ThanhLy", "CN_ThanhLy", new { idhd = "ID_replaCe" })';
                    url = url.replace('ID_replaCe', idSelected);
                    window.location.href = url;
                } else {
                    $.notify({
                        // options
                        message: 'Bạn chưa chọn dòng nào'
                    }, {
                        // settings
                        type: 'danger'
                    });
                }

            });
            $('#btnXuPhat').click(function () {
                var idSelected = $("#example .selected").attr("id");
                if (idSelected != undefined) {
                    var url = '@Url.Action("Edit_XuPhatTranhChap", "CN_HopDong", new { idhd = "ID_replaCe" })';
                    url = url.replace('ID_replaCe', idSelected);
                    window.location.href = url;
                } else {
                    $.notify({
                        // options
                        message: 'Bạn chưa chọn dòng nào'
                    }, {
                        // settings
                        type: 'danger'
                    });
                }

            }); 
            $('#btnHetHan').click(function () {
                var url = '@Url.Action("Index_HetHanDieuChinh", "CN_HopDong")';
                window.location.href = url;
            });
            $('#btnDongYDB').click(function () {
                Loading();
                $.ajax({
                    url: "/CN_HopDong/DongBo_CNHopDong",
                    dataType: "json",
                    type: "POST",
                    contentType: 'application/json; charset=utf-8',
                    async: true,
                    processData: false,
                    cache: false,
                    success: function (data) {
                        if (data == "1") {
                            LoadingHide();
                            $.notify({
                                title: '<strong>Thông báo</strong>:',
                                message: 'Đồng bộ thành công'
                            }, {
                                type: 'info'
                            });
                        }
                        else {
                            $.notify({
                                title: '<strong>Thông báo</strong>:',
                                message: data + 'Có lỗi xảy ra khi đồng bộ'
                            }, {
                                type: 'danger'
                            });

                            console.log(data);
                            LoadingHide();
                        }
                    },
                    error: function (xhr) {
                        console.log("error: " + data + " status: " + status + " er:" + er);
                    }
                });

            });
        });
    </script>
    <script src="~/Scripts/bootstrap-toggle.min.js"></script>
}